### ISSUE TITLE
underlying problem

### ISSUE THREAD

**Issue by hero5512** [tokenInsight/coin-tools#2]
Some ERC20 standard transfer functions do not revert if the transaction fails, which can result in part of the recipients receiving funds. To avoid this issue, you can consider using the safeTransfer function from the OpenZeppelin library. I think.

**Comment by zeng3234** [comment]
Thank you for your suggestion. Initially, I did consider using safeTransfer. Considering that the usdt.transfer method always returns false on the TRON chain, I chose to use the current interface form for transfer without checking the return value. This allows me to deploy the same code on multiple chains. 

After all, most tokens use safeMath in the transfer, and will revert if they fail; However, I have also seen some tokens on etherscan that return false when the conditions are insufficient. We will make further improvements in the next version.
